#!/usr/bin/env python3

import math

velocity_factor = 0.2
velocity_curve  = 60


# max human speed about 3ms
# slowest sensible speed around 64 ms
#
# we want near perfect lookups with a log curve

def microsToVelocity(micros):
    if(micros <= 0):
        return 127
    millis = micros/1000
    velocity = velocity_curve * math.log(velocity_factor*millis)
    if velocity < 0:
        return 127
    if (velocity > 127):
        return 1
    return 127-math.floor(velocity)

def outputCArray(name, length, callback):
    print("static const char {}[{}] = {{".format(name, length))
    for i in range(length):
        print("  {},".format(callback(i<<8)))
    print("};")


print(
'''/*
*
*  THIS FILE IS AUTO GENERATED
*
*  Generated by tools/genlookup.py - do not modify this filedirectly , it might be overwritten
*
*/
'''
)

outputCArray("velocity_log", 256, microsToVelocity)

